---
  - name: "Deploying on the kubernetes cluster"
    hosts: all
    # become: true
    remote_user: deomnai
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
    vars_files:
      - my_vault.yml
    vars:
      docker_user: deomani721
    roles:
      - deploy-filebeats-logstash
      - add-secrets-configmap
      - refresh-deployments