---
  - name: Deploying logstash and filebeats inside the kubernetes cluster
      ansible.builtin.shell: |
        helm upgrade --install filebeat kubeDeploy/filebeat
        helm upgrade --install logstash kubeDeploy/logstash
      environment:
        KUBECONFIG: "/Users/deomani/confKube"