apiVersion: v1
kind: Service
metadata:
  name: backend-deployment
  labels:
    name: backend-deployment
spec:
  selector:
    app: backend-deployment
  type: NodePort
  ports:
    - name: http
      port: 8500
      targetPort: 8500
      nodePort: 30163
      protocol: TCP
