apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradeus-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradeus-frontend-deployment
  template:
    metadata:
      labels:
        app: gradeus-frontend-deployment
    spec:
      containers:
        - name: gradeus-frontend-deployment
          image: deomoney721/gradeus-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gradeus-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gradeus-frontend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50