apiVersion: apps/v1 
kind: Deployment    
metadata:   # Data that helps  uniquely identify the object (using name, UID and namespace)          
  name: gradeus-frontend-deployment
spec:               
  selector:        
    matchLabels:
      app: gradeus-frontend-deployment
  replicas: 1       
  template:
    metadata:
      labels:        
        app: gradeus-frontend-deployment
    spec:
      containers:
        - name: gradeus-frontend-deployment
          image: deomoney721/gradeus-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80